var languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
var firtElement = [languages[0]];
console.log('the first element of the array is:', firtElement);
var thridElement = [languages[2]];
console.log('the 3rd element of the array is:', thridElement);
var length = languages.length;
console.log('The length of the array is:',length);
var lastElement = languages[length-1];
console.log('The last element of the array is:',lastElement);
